INSERT INTO Tarea (id, nombre, categoria) VALUES
(1, 'Registrarse', 'BUSCADORES'),
(2, 'Iniciar sesión', 'BUSCADORES'),
(3, 'Búsqueda con palabras', 'BUSCADORES'),
(4, 'Búsqueda con imágenes', 'BUSCADORES'),
(5, 'Búsqueda en diferentes idiomas', 'BUSCADORES'),
(6, 'Filtrar resultados', 'BUSCADORES'),
(7, 'Cambiar idioma', 'BUSCADORES'),
(8, 'Búsqueda predictiva', 'BUSCADORES'),
(9, 'Sugerencias de búsqueda', 'BUSCADORES'),
(10, 'Registrarse', 'BLOGS'),
(11, 'Iniciar sesión', 'BLOGS'),
(12, 'Búsqueda con palabras', 'BLOGS'),
(13, 'Ver últimas novedades/noticias', 'BLOGS'),
(14, 'Compartir contenido', 'BLOGS'),
(15, 'Comentar contenido', 'BLOGS'),
(16, 'Ver etiquetas', 'BLOGS'),
(17, 'Valorar contenido', 'BLOGS'),
(18, 'Registrarse', 'FOROS'),
(19, 'Iniciar sesión', 'FOROS'),
(20, 'Búsqueda con palabras', 'FOROS'),
(21, 'Ver publicaciones populares', 'FOROS'),
(22, 'Ver últimas publicaciones', 'FOROS'),
(23, 'Publicar tema', 'FOROS'),
(24, 'Citar un tema/publicación', 'FOROS'),
(25, 'Responder tema', 'FOROS'),
(26, 'Ver perfil de un usuario', 'FOROS'),
(27, 'Ver mensajes de un usuario', 'FOROS'),
(28, 'Registrarse', 'REDES_SOCIALES'),
(29, 'Iniciar sesión', 'REDES_SOCIALES'),
(30, 'Buscar contenido', 'REDES_SOCIALES'),
(31, 'Publicar contenido', 'REDES_SOCIALES'),
(32, 'Compartir contenido', 'REDES_SOCIALES'),
(33, 'Enviar mensajes privados', 'REDES_SOCIALES'),
(34, 'Ver perfil de un usuario', 'REDES_SOCIALES'),
(35, 'Editar mi perfil', 'REDES_SOCIALES'),
(36, 'Ver eitquetas', 'REDES_SOCIALES'),
(37, 'Registrarse', 'TRANSACIONALES'),
(38, 'Iniciar sesión', 'TRANSACIONALES'),
(39, 'Realizar transferencia', 'TRANSACIONALES'),
(40, 'Ver recibos', 'TRANSACIONALES'),
(41, 'Ver saldo', 'TRANSACIONALES'),
(42, 'Ver mis cuentas bancarias', 'TRANSACIONALES'),
(43, 'Ver mis tarjetas', 'TRANSACIONALES'),
(44, 'Solicitar préstamo', 'TRANSACIONALES'),
(45, 'Ver información de una cuenta', 'TRANSACIONALES'),
(46, 'Registrarse', 'COMERCIO_ELECTRONICO'),
(47, 'Iniciar sesión', 'COMERCIO_ELECTRONICO'),
(48, 'Búsqueda con palabras', 'COMERCIO_ELECTRONICO'),
(49, 'Buscar por categoría', 'COMERCIO_ELECTRONICO'),
(50, 'Ver información producto', 'COMERCIO_ELECTRONICO'),
(51, 'Valorar producto', 'COMERCIO_ELECTRONICO'),
(52, 'Realizar pedido', 'COMERCIO_ELECTRONICO'),
(53, 'Cancelar pedido', 'COMERCIO_ELECTRONICO'),
(54, 'Realizar reclamación', 'COMERCIO_ELECTRONICO'),
(55, 'Añadir producto a lista de deseos', 'COMERCIO_ELECTRONICO'),
(56, 'Registrarse', 'CORREO_ELECTRONICO'),
(57, 'Iniciar sesión', 'CORREO_ELECTRONICO'),
(58, 'Redactar correo', 'CORREO_ELECTRONICO'),
(59, 'Filtrar correos', 'CORREO_ELECTRONICO'),
(60, 'Eliminar correo', 'CORREO_ELECTRONICO'),
(61, 'Crear carpetas', 'CORREO_ELECTRONICO'),
(62, 'Responder correo', 'CORREO_ELECTRONICO'),
(63, 'Bloquear emisor', 'CORREO_ELECTRONICO'),
(64, 'Búsqueda por palabras', 'CORREO_ELECTRONICO'),
(65, 'Registrarse', 'ENTRETENIMIENTO'),
(66, 'Iniciar sesión', 'ENTRETENIMIENTO'),
(67, 'Búsqueda con palabras', 'ENTRETENIMIENTO'),
(68, 'Buscar por categoría', 'ENTRETENIMIENTO'),
(69, 'Ver contenido/juego', 'ENTRETENIMIENTO'),
(70, 'Añadir a favoritos', 'ENTRETENIMIENTO'),
(71, 'Valorar contenido/juego', 'ENTRETENIMIENTO'),
(72, 'Ver últimas novedades', 'ENTRETENIMIENTO'),
(73, 'Ver sugerencias', 'ENTRETENIMIENTO'),
(74, 'Iniciar sesión', 'ACADEMICO'),
(75, 'Ver anuncios', 'ACADEMICO'),
(76, 'Ver tareas', 'ACADEMICO'),
(77, 'Descargar material', 'ACADEMICO'),
(78, 'Contactar con un profesor', 'ACADEMICO'),
(79, 'Ver notas de exámenes', 'ACADEMICO'),
(80, 'Filtrar asignaturas', 'ACADEMICO'),
(81, 'Ver planificación/calendario asignatura', 'ACADEMICO'),
(82, 'Registrarse', 'COLABORATIVAS'),
(83, 'Iniciar sesión', 'COLABORATIVAS'),
(84, 'Búsqueda por palabras', 'COLABORATIVAS'),
(85, 'Ver recientes', 'COLABORATIVAS'),
(86, 'Crear nuevo documento', 'COLABORATIVAS'),
(87, 'Filtrar documentos', 'COLABORATIVAS'),
(88, 'Descargar un documento', 'COLABORATIVAS'),
(89, 'Añadir participantes', 'COLABORATIVAS'),
(90, 'Comunicarse con los participantes', 'COLABORATIVAS'),
(91, 'Registrarse', 'DESCARGAS'),
(92, 'Iniciar sesión', 'DESCARGAS'),
(93, 'Búsqueda por palabras', 'DESCARGAS'),
(94, 'Filtrar descargas', 'DESCARGAS'),
(95, 'Buscar por categoría', 'DESCARGAS'),
(96, 'Descargar contenido', 'DESCARGAS'),
(97, 'Compartir descarga', 'DESCARGAS'),
(98, 'Valorar descarga', 'DESCARGAS'),
(99, 'Ver descripción descarga', 'DESCARGAS'),
(100, 'Ver información empresa', 'CORPORATIVA'),
(101, 'Ver tarifas', 'CORPORATIVA'),
(102, 'Ver servicios proporcionados', 'CORPORATIVA'),
(103, 'Ver información de contacto', 'CORPORATIVA'),
(104, 'Ver enlaces a redes sociales', 'CORPORATIVA'),
(105, 'Cambiar idioma de la página', 'CORPORATIVA'),
(106, 'Registrarse', 'SERVICIOS'),
(107, 'Iniciar sesión', 'SERVICIOS'),
(108, 'Usar servicio', 'SERVICIOS'),
(109, 'Ver ayuda', 'SERVICIOS'),
(110, 'Ver información del servicio', 'SERVICIOS'),
(111, 'Cambiar idioma de la página', 'SERVICIOS');
