INSERT INTO Tarea (id, nombre, categoria) VALUES
(1, 'Registrarse', 'Buscadores/Portales'),
(2, 'Iniciar sesión', 'Buscadores/Portales'),
(3, 'Búsqueda con palabras', 'Buscadores/Portales'),
(4, 'Búsqueda con imágenes', 'Buscadores/Portales'),
(5, 'Búsqueda en diferentes idiomas', 'Buscadores/Portales'),
(6, 'Filtrar resultados', 'Buscadores/Portales'),
(7, 'Cambiar idioma', 'Buscadores/Portales'),
(8, 'Búsqueda predictiva', 'Buscadores/Portales'),
(9, 'Sugerencias de búsqueda', 'Buscadores/Portales'),
(10, 'Registrarse', 'Blogs/Informativas'),
(11, 'Iniciar sesión', 'Blogs/Informativas'),
(12, 'Búsqueda con palabras', 'Blogs/Informativas'),
(13, 'Ver últimas novedades/noticias', 'Blogs/Informativas'),
(14, 'Compartir contenido', 'Blogs/Informativas'),
(15, 'Comentar contenido', 'Blogs/Informativas'),
(16, 'Ver etiquetas', 'Blogs/Informativas'),
(17, 'Valorar contenido', 'Blogs/Informativas'),
(18, 'Registrarse', 'Foros/Interacción'),
(19, 'Iniciar sesión', 'Foros/Interacción'),
(20, 'Búsqueda con palabras', 'Foros/Interacción'),
(21, 'Ver publicaciones populares', 'Foros/Interacción'),
(22, 'Ver últimas publicaciones', 'Foros/Interacción'),
(23, 'Publicar tema', 'Foros/Interacción'),
(24, 'Citar un tema/publicación', 'Foros/Interacción'),
(25, 'Responder tema', 'Foros/Interacción'),
(26, 'Ver perfil de un usuario', 'Foros/Interacción'),
(27, 'Ver mensajes de un usuario', 'Foros/Interacción'),
(28, 'Registrarse', 'Redes sociales'),
(29, 'Iniciar sesión', 'Redes sociales'),
(30, 'Buscar contenido', 'Redes sociales'),
(31, 'Publicar contenido', 'Redes sociales'),
(32, 'Compartir contenido', 'Redes sociales'),
(33, 'Enviar mensajes privados', 'Redes sociales'),
(34, 'Ver perfil de un usuario', 'Redes sociales'),
(35, 'Editar mi perfil', 'Redes sociales'),
(36, 'Ver eitquetas', 'Redes sociales'),
(37, 'Registrarse', 'Transaccionales'),
(38, 'Iniciar sesión', 'Transaccionales'),
(39, 'Realizar transferencia', 'Transaccionales'),
(40, 'Ver recibos', 'Transaccionales'),
(41, 'Ver saldo', 'Transaccionales'),
(42, 'Ver mis cuentas bancarias', 'Transaccionales'),
(43, 'Ver mis tarjetas', 'Transaccionales'),
(44, 'Solicitar préstamo', 'Transaccionales'),
(45, 'Ver información de una cuenta', 'Transaccionales'),
(46, 'Registrarse', 'Comercio electrónico'),
(47, 'Iniciar sesión', 'Comercio electrónico'),
(48, 'Búsqueda con palabras', 'Comercio electrónico'),
(49, 'Buscar por categoría', 'Comercio electrónico'),
(50, 'Ver información producto', 'Comercio electrónico'),
(51, 'Valorar producto', 'Comercio electrónico'),
(52, 'Realizar pedido', 'Comercio electrónico'),
(53, 'Cancelar pedido', 'Comercio electrónico'),
(54, 'Realizar reclamación', 'Comercio electrónico'),
(55, 'Añadir producto a lista de deseos', 'Comercio electrónico'),
(56, 'Registrarse', 'Correo electrónico'),
(57, 'Iniciar sesión', 'Correo electrónico'),
(58, 'Redactar correo', 'Correo electrónico'),
(59, 'Filtrar correos', 'Correo electrónico'),
(60, 'Eliminar correo', 'Correo electrónico'),
(61, 'Crear carpetas', 'Correo electrónico'),
(62, 'Responder correo', 'Correo electrónico'),
(63, 'Bloquear emisor', 'Correo electrónico'),
(64, 'Búsqueda por palabras', 'Correo electrónico'),
(65, 'Registrarse', 'Entretenimiento'),
(66, 'Iniciar sesión', 'Entretenimiento'),
(67, 'Búsqueda con palabras', 'Entretenimiento'),
(68, 'Buscar por categoría', 'Entretenimiento'),
(69, 'Ver contenido/juego', 'Entretenimiento'),
(70, 'Añadir a favoritos', 'Entretenimiento'),
(71, 'Valorar contenido/juego', 'Entretenimiento'),
(72, 'Ver últimas novedades', 'Entretenimiento'),
(73, 'Ver sugerencias', 'Entretenimiento'),
(74, 'Iniciar sesión', 'Académico'),
(75, 'Ver anuncios', 'Académico'),
(76, 'Ver tareas', 'Académico'),
(77, 'Descargar material', 'Académico'),
(78, 'Contactar con un profesor', 'Académico'),
(79, 'Ver notas de exámenes', 'Académico'),
(80, 'Filtrar asignaturas', 'Académico'),
(81, 'Ver planificación/calendario asignatura', 'Académico'),
(82, 'Registrarse', 'Colaborativas'),
(83, 'Iniciar sesión', 'Colaborativas'),
(84, 'Búsqueda por palabras', 'Colaborativas'),
(85, 'Ver recientes', 'Colaborativas'),
(86, 'Crear nuevo documento', 'Colaborativas'),
(87, 'Filtrar documentos', 'Colaborativas'),
(88, 'Descargar un documento', 'Colaborativas'),
(89, 'Añadir participantes', 'Colaborativas'),
(90, 'Comunicarse con los participantes', 'Colaborativas'),
(91, 'Registrarse', 'Descargas'),
(92, 'Iniciar sesión', 'Descargas'),
(93, 'Búsqueda por palabras', 'Descargas'),
(94, 'Filtrar descargas', 'Descargas'),
(95, 'Buscar por categoría', 'Descargas'),
(96, 'Descargar contenido', 'Descargas'),
(97, 'Compartir descarga', 'Descargas'),
(98, 'Valorar descarga', 'Descargas'),
(99, 'Ver descripción descarga', 'Descargas'),
(100, 'Ver información empresa', 'Corporativa/Entidades públicas'),
(101, 'Ver tarifas', 'Corporativa/Entidades públicas'),
(102, 'Ver servicios proporcionados', 'Corporativa/Entidades públicas'),
(103, 'Ver información de contacto', 'Corporativa/Entidades públicas'),
(104, 'Ver enlaces a redes sociales', 'Corporativa/Entidades públicas'),
(105, 'Cambiar idioma de la página', 'Corporativa/Entidades públicas'),
(106, 'Registrarse', 'Servicios'),
(107, 'Iniciar sesión', 'Servicios'),
(108, 'Usar servicio', 'Servicios'),
(109, 'Ver ayuda', 'Servicios'),
(110, 'Ver información del servicio', 'Servicios'),
(111, 'Cambiar idioma de la página', 'Servicios');