export enum Categoria {
    'Buscadores/Portales',
    'Blogs/Informativas',
    'Foros/Interaccción',
    'Redes Sociales',
    'Transacionales',
    'Comercio electrónico',
    'Correo electrónico',
    'Entretenimiento',
    'Académico',
    'Colaborativas',
    'Descargas',
    'Corporativa/Entidades públicas',
    'Servicios',
  }