export enum Categoria {
  'Search Engines/Portals',
  'Blogs/Informative',
  'Forums/Interaction',
  'Social Networks',
  'Transactional',
  'E-commerce',
  'Email',
  'Entertainment',
  'Academic',
  'Collaborative',
  'Downloads',
  'Corporate/Public Entities',
  'Services',
}